### ISSUE TITLE
Game crashing when selecting a new structure while one is already selected

### ISSUE THREAD

**Issue by MooMoo7661** [ScalarVector1/StructureHelper#19]
![structurehelper](https://github.com/ScalarVector1/StructureHelper/assets/88794733/def23de3-01fa-491d-8d78-489831ee8591)

[client.log](https://github.com/ScalarVector1/StructureHelper/files/13532128/client.log)

**Comment by MooMoo7661** [comment]
This makes it very difficult to do anything since (afaik) there is no way to deselect a structure.

**Comment by ScalarVector1** [comment]
I'll take a look into this, for now you can deselect a structure with a right click I believe

**Comment by ScalarVector1** [comment]
This should be resolved with 2.4.0
