### ISSUE TITLE
GenerateStructure failing after renaming mod's internal name

### ISSUE THREAD

**Issue by MooMoo7661** [ScalarVector1/StructureHelper#20]
Previous mod name was "OneBlock", renamed it to "UltimateSkyblock". Saw an old issue that was marked as completed, but no answer or anything I could see for how to fix it.

![image](https://github.com/ScalarVector1/StructureHelper/assets/88794733/a4b746f4-5194-470e-99d3-22913e3a3c78)

**Comment by ScalarVector1** [comment]
There isnt really much I can do about this -- modded tiles are identified uniquely by their internal name, which includes the mod internal name. There isnt really a way to both be forward compatible if mod internal names change and not conflict with other mods that have the same internal name for their tiles. In general there is very, very little reason to ever change a mod internal name. Your best bet if you absolutely must change the name would be to place your structures with the test wand before and correct and re-save them after changing your mods internal name.

**Comment by MooMoo7661** [comment]
Ah, my bad. I completely forgot that the structure had a modded tile 😅
I couldn't for the life of me figure out why it would still be detecting the old mod name.
